// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhNewsInfo.proto

package com.dzhyun.proto;

public final class DzhNewsInfo {
  private DzhNewsInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsInfoValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string ver = 1;
    /**
     * <code>required string ver = 1;</code>
     */
    boolean hasVer();
    /**
     * <code>required string ver = 1;</code>
     */
    java.lang.String getVer();
    /**
     * <code>required string ver = 1;</code>
     */
    com.google.protobuf.ByteString
        getVerBytes();

    // required uint32 act = 2;
    /**
     * <code>required uint32 act = 2;</code>
     */
    boolean hasAct();
    /**
     * <code>required uint32 act = 2;</code>
     */
    int getAct();

    // required uint64 newsID = 3;
    /**
     * <code>required uint64 newsID = 3;</code>
     */
    boolean hasNewsID();
    /**
     * <code>required uint64 newsID = 3;</code>
     */
    long getNewsID();

    // optional string newsTitle = 4;
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    boolean hasNewsTitle();
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    java.lang.String getNewsTitle();
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    com.google.protobuf.ByteString
        getNewsTitleBytes();
  }
  /**
   * Protobuf type {@code dzhyun.NewsInfoValue}
   *
   * <pre>
   * -&gt;MSG
   * </pre>
   */
  public static final class NewsInfoValue extends
      com.google.protobuf.GeneratedMessage
      implements NewsInfoValueOrBuilder {
    // Use NewsInfoValue.newBuilder() to construct.
    private NewsInfoValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewsInfoValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewsInfoValue defaultInstance;
    public static NewsInfoValue getDefaultInstance() {
      return defaultInstance;
    }

    public NewsInfoValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewsInfoValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ver_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              act_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newsID_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              newsTitle_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhNewsInfo.internal_static_dzhyun_NewsInfoValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhNewsInfo.internal_static_dzhyun_NewsInfoValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.class, com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.Builder.class);
    }

    public static com.google.protobuf.Parser<NewsInfoValue> PARSER =
        new com.google.protobuf.AbstractParser<NewsInfoValue>() {
      public NewsInfoValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsInfoValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewsInfoValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string ver = 1;
    public static final int VER_FIELD_NUMBER = 1;
    private java.lang.Object ver_;
    /**
     * <code>required string ver = 1;</code>
     */
    public boolean hasVer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ver = 1;</code>
     */
    public java.lang.String getVer() {
      java.lang.Object ref = ver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVerBytes() {
      java.lang.Object ref = ver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 act = 2;
    public static final int ACT_FIELD_NUMBER = 2;
    private int act_;
    /**
     * <code>required uint32 act = 2;</code>
     */
    public boolean hasAct() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 act = 2;</code>
     */
    public int getAct() {
      return act_;
    }

    // required uint64 newsID = 3;
    public static final int NEWSID_FIELD_NUMBER = 3;
    private long newsID_;
    /**
     * <code>required uint64 newsID = 3;</code>
     */
    public boolean hasNewsID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 newsID = 3;</code>
     */
    public long getNewsID() {
      return newsID_;
    }

    // optional string newsTitle = 4;
    public static final int NEWSTITLE_FIELD_NUMBER = 4;
    private java.lang.Object newsTitle_;
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    public boolean hasNewsTitle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    public java.lang.String getNewsTitle() {
      java.lang.Object ref = newsTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newsTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string newsTitle = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNewsTitleBytes() {
      java.lang.Object ref = newsTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newsTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ver_ = "";
      act_ = 0;
      newsID_ = 0L;
      newsTitle_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAct()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewsID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getVerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, act_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, newsID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNewsTitleBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getVerBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, act_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, newsID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNewsTitleBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhNewsInfo.NewsInfoValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.NewsInfoValue}
     *
     * <pre>
     * -&gt;MSG
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.DzhNewsInfo.NewsInfoValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhNewsInfo.internal_static_dzhyun_NewsInfoValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhNewsInfo.internal_static_dzhyun_NewsInfoValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.class, com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ver_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        act_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        newsID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        newsTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhNewsInfo.internal_static_dzhyun_NewsInfoValue_descriptor;
      }

      public com.dzhyun.proto.DzhNewsInfo.NewsInfoValue getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhNewsInfo.NewsInfoValue build() {
        com.dzhyun.proto.DzhNewsInfo.NewsInfoValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhNewsInfo.NewsInfoValue buildPartial() {
        com.dzhyun.proto.DzhNewsInfo.NewsInfoValue result = new com.dzhyun.proto.DzhNewsInfo.NewsInfoValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ver_ = ver_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.act_ = act_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.newsID_ = newsID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newsTitle_ = newsTitle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhNewsInfo.NewsInfoValue) {
          return mergeFrom((com.dzhyun.proto.DzhNewsInfo.NewsInfoValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhNewsInfo.NewsInfoValue other) {
        if (other == com.dzhyun.proto.DzhNewsInfo.NewsInfoValue.getDefaultInstance()) return this;
        if (other.hasVer()) {
          bitField0_ |= 0x00000001;
          ver_ = other.ver_;
          onChanged();
        }
        if (other.hasAct()) {
          setAct(other.getAct());
        }
        if (other.hasNewsID()) {
          setNewsID(other.getNewsID());
        }
        if (other.hasNewsTitle()) {
          bitField0_ |= 0x00000008;
          newsTitle_ = other.newsTitle_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVer()) {
          
          return false;
        }
        if (!hasAct()) {
          
          return false;
        }
        if (!hasNewsID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhNewsInfo.NewsInfoValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhNewsInfo.NewsInfoValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string ver = 1;
      private java.lang.Object ver_ = "";
      /**
       * <code>required string ver = 1;</code>
       */
      public boolean hasVer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public java.lang.String getVer() {
        java.lang.Object ref = ver_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVerBytes() {
        java.lang.Object ref = ver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder setVer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder clearVer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ver_ = getDefaultInstance().getVer();
        onChanged();
        return this;
      }
      /**
       * <code>required string ver = 1;</code>
       */
      public Builder setVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ver_ = value;
        onChanged();
        return this;
      }

      // required uint32 act = 2;
      private int act_ ;
      /**
       * <code>required uint32 act = 2;</code>
       */
      public boolean hasAct() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 act = 2;</code>
       */
      public int getAct() {
        return act_;
      }
      /**
       * <code>required uint32 act = 2;</code>
       */
      public Builder setAct(int value) {
        bitField0_ |= 0x00000002;
        act_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 act = 2;</code>
       */
      public Builder clearAct() {
        bitField0_ = (bitField0_ & ~0x00000002);
        act_ = 0;
        onChanged();
        return this;
      }

      // required uint64 newsID = 3;
      private long newsID_ ;
      /**
       * <code>required uint64 newsID = 3;</code>
       */
      public boolean hasNewsID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 newsID = 3;</code>
       */
      public long getNewsID() {
        return newsID_;
      }
      /**
       * <code>required uint64 newsID = 3;</code>
       */
      public Builder setNewsID(long value) {
        bitField0_ |= 0x00000004;
        newsID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 newsID = 3;</code>
       */
      public Builder clearNewsID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newsID_ = 0L;
        onChanged();
        return this;
      }

      // optional string newsTitle = 4;
      private java.lang.Object newsTitle_ = "";
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public boolean hasNewsTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public java.lang.String getNewsTitle() {
        java.lang.Object ref = newsTitle_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newsTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNewsTitleBytes() {
        java.lang.Object ref = newsTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newsTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public Builder setNewsTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        newsTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public Builder clearNewsTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newsTitle_ = getDefaultInstance().getNewsTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string newsTitle = 4;</code>
       */
      public Builder setNewsTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        newsTitle_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.NewsInfoValue)
    }

    static {
      defaultInstance = new NewsInfoValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.NewsInfoValue)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_NewsInfoValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_NewsInfoValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021dzhNewsInfo.proto\022\006dzhyun\"L\n\rNewsInfoV" +
      "alue\022\013\n\003ver\030\001 \002(\t\022\013\n\003act\030\002 \002(\r\022\016\n\006newsID" +
      "\030\003 \002(\004\022\021\n\tnewsTitle\030\004 \001(\tB\022\n\020com.dzhyun." +
      "proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dzhyun_NewsInfoValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dzhyun_NewsInfoValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_NewsInfoValue_descriptor,
              new java.lang.String[] { "Ver", "Act", "NewsID", "NewsTitle", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
