// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CldChuQuanXinXi.proto

package com.dzhyun.proto;

public final class ProtoDivideWarrant {
  private ProtoDivideWarrant() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChuQuanXinXiOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string obj = 2;
    /**
     * <code>required string obj = 2;</code>
     */
    boolean hasObj();
    /**
     * <code>required string obj = 2;</code>
     */
    java.lang.String getObj();
    /**
     * <code>required string obj = 2;</code>
     */
    com.google.protobuf.ByteString
        getObjBytes();

    // required string chuQuanRiQi = 3;
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    boolean hasChuQuanRiQi();
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    java.lang.String getChuQuanRiQi();
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    com.google.protobuf.ByteString
        getChuQuanRiQiBytes();

    // required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];
    /**
     * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
     *
     * <pre>
     * 复权类型
     * </pre>
     */
    boolean hasFuQuanLeiXing();
    /**
     * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
     *
     * <pre>
     * 复权类型
     * </pre>
     */
    com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing getFuQuanLeiXing();

    // optional int32 meiGuXianJinFenHong = 5;
    /**
     * <code>optional int32 meiGuXianJinFenHong = 5;</code>
     *
     * <pre>
     * 每股现金分红
     * </pre>
     */
    boolean hasMeiGuXianJinFenHong();
    /**
     * <code>optional int32 meiGuXianJinFenHong = 5;</code>
     *
     * <pre>
     * 每股现金分红
     * </pre>
     */
    int getMeiGuXianJinFenHong();

    // optional int32 meiGuHongGuShu = 6;
    /**
     * <code>optional int32 meiGuHongGuShu = 6;</code>
     *
     * <pre>
     * 每股红股数
     * </pre>
     */
    boolean hasMeiGuHongGuShu();
    /**
     * <code>optional int32 meiGuHongGuShu = 6;</code>
     *
     * <pre>
     * 每股红股数
     * </pre>
     */
    int getMeiGuHongGuShu();

    // optional int32 meiGuPeiGuShu = 7;
    /**
     * <code>optional int32 meiGuPeiGuShu = 7;</code>
     *
     * <pre>
     * 每股配股数
     * </pre>
     */
    boolean hasMeiGuPeiGuShu();
    /**
     * <code>optional int32 meiGuPeiGuShu = 7;</code>
     *
     * <pre>
     * 每股配股数
     * </pre>
     */
    int getMeiGuPeiGuShu();

    // optional int32 meiGuPeiGuJia = 8;
    /**
     * <code>optional int32 meiGuPeiGuJia = 8;</code>
     *
     * <pre>
     * 每股配股价
     * </pre>
     */
    boolean hasMeiGuPeiGuJia();
    /**
     * <code>optional int32 meiGuPeiGuJia = 8;</code>
     *
     * <pre>
     * 每股配股价
     * </pre>
     */
    int getMeiGuPeiGuJia();

    // optional int32 meiGuChaiXiShu = 9;
    /**
     * <code>optional int32 meiGuChaiXiShu = 9;</code>
     *
     * <pre>
     * 每股拆细数
     * </pre>
     */
    boolean hasMeiGuChaiXiShu();
    /**
     * <code>optional int32 meiGuChaiXiShu = 9;</code>
     *
     * <pre>
     * 每股拆细数
     * </pre>
     */
    int getMeiGuChaiXiShu();

    // optional int32 tDayClose = 10;
    /**
     * <code>optional int32 tDayClose = 10;</code>
     *
     * <pre>
     * t日收盘价
     * </pre>
     */
    boolean hasTDayClose();
    /**
     * <code>optional int32 tDayClose = 10;</code>
     *
     * <pre>
     * t日收盘价
     * </pre>
     */
    int getTDayClose();

    // optional int32 tLastDayClose = 11;
    /**
     * <code>optional int32 tLastDayClose = 11;</code>
     *
     * <pre>
     * t-1日收盘价
     * </pre>
     */
    boolean hasTLastDayClose();
    /**
     * <code>optional int32 tLastDayClose = 11;</code>
     *
     * <pre>
     * t-1日收盘价
     * </pre>
     */
    int getTLastDayClose();

    // optional int32 fuQuanXiShu = 12;
    /**
     * <code>optional int32 fuQuanXiShu = 12;</code>
     *
     * <pre>
     * 复权细数
     * </pre>
     */
    boolean hasFuQuanXiShu();
    /**
     * <code>optional int32 fuQuanXiShu = 12;</code>
     *
     * <pre>
     * 复权细数
     * </pre>
     */
    int getFuQuanXiShu();

    // optional string tLastDay = 13;
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    boolean hasTLastDay();
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    java.lang.String getTLastDay();
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    com.google.protobuf.ByteString
        getTLastDayBytes();

    // optional int32 guLiXiShu = 14;
    /**
     * <code>optional int32 guLiXiShu = 14;</code>
     *
     * <pre>
     * 股利系数
     * </pre>
     */
    boolean hasGuLiXiShu();
    /**
     * <code>optional int32 guLiXiShu = 14;</code>
     *
     * <pre>
     * 股利系数
     * </pre>
     */
    int getGuLiXiShu();

    // optional int32 ziBenXiShu = 15;
    /**
     * <code>optional int32 ziBenXiShu = 15;</code>
     *
     * <pre>
     * 资本系数
     * </pre>
     */
    boolean hasZiBenXiShu();
    /**
     * <code>optional int32 ziBenXiShu = 15;</code>
     *
     * <pre>
     * 资本系数
     * </pre>
     */
    int getZiBenXiShu();

    // optional int32 fuQuanXiShuDzh = 16;
    /**
     * <code>optional int32 fuQuanXiShuDzh = 16;</code>
     *
     * <pre>
     * 复权系数(大智慧)
     * </pre>
     */
    boolean hasFuQuanXiShuDzh();
    /**
     * <code>optional int32 fuQuanXiShuDzh = 16;</code>
     *
     * <pre>
     * 复权系数(大智慧)
     * </pre>
     */
    int getFuQuanXiShuDzh();

    // required string updateTime = 17;
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    boolean hasUpdateTime();
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    java.lang.String getUpdateTime();
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();
  }
  /**
   * Protobuf type {@code dzhyun.ChuQuanXinXi}
   */
  public static final class ChuQuanXinXi extends
      com.google.protobuf.GeneratedMessage
      implements ChuQuanXinXiOrBuilder {
    // Use ChuQuanXinXi.newBuilder() to construct.
    private ChuQuanXinXi(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChuQuanXinXi(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChuQuanXinXi defaultInstance;
    public static ChuQuanXinXi getDefaultInstance() {
      return defaultInstance;
    }

    public ChuQuanXinXi getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChuQuanXinXi(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              obj_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              chuQuanRiQi_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing value = com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                fuQuanLeiXing_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              meiGuXianJinFenHong_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              meiGuHongGuShu_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              meiGuPeiGuShu_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              meiGuPeiGuJia_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              meiGuChaiXiShu_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              tDayClose_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              tLastDayClose_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              fuQuanXiShu_ = input.readInt32();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              tLastDay_ = input.readBytes();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              guLiXiShu_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              ziBenXiShu_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              fuQuanXiShuDzh_ = input.readInt32();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.ProtoDivideWarrant.internal_static_dzhyun_ChuQuanXinXi_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.ProtoDivideWarrant.internal_static_dzhyun_ChuQuanXinXi_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.class, com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.Builder.class);
    }

    public static com.google.protobuf.Parser<ChuQuanXinXi> PARSER =
        new com.google.protobuf.AbstractParser<ChuQuanXinXi>() {
      public ChuQuanXinXi parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChuQuanXinXi(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChuQuanXinXi> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing}
     *
     * <pre>
     * 枚举类型-上市状态
     * </pre>
     */
    public enum EUM_FuQuanLeiXing
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FuQuan_JiaGeFuQuan_KaoLvHongLi = 1;</code>
       *
       * <pre>
       * 价格复权:考虑红利再投资
       * </pre>
       */
      FuQuan_JiaGeFuQuan_KaoLvHongLi(0, 1),
      /**
       * <code>FuQuan_JiaGeFuQuan_BuKaoLvHongLi = 2;</code>
       *
       * <pre>
       * 价格复权:不考虑红利再投资
       * </pre>
       */
      FuQuan_JiaGeFuQuan_BuKaoLvHongLi(1, 2),
      /**
       * <code>FuQuan_JingZhiFuQuan_KaoLvHongLi = 3;</code>
       *
       * <pre>
       * 净值复权:考虑红利再投资
       * </pre>
       */
      FuQuan_JingZhiFuQuan_KaoLvHongLi(2, 3),
      /**
       * <code>FuQuan_JingZhiFuQuan_BuKaoLvHongLi = 4;</code>
       *
       * <pre>
       * 净值复权:不考虑红利再投资
       * </pre>
       */
      FuQuan_JingZhiFuQuan_BuKaoLvHongLi(3, 4),
      ;

      /**
       * <code>FuQuan_JiaGeFuQuan_KaoLvHongLi = 1;</code>
       *
       * <pre>
       * 价格复权:考虑红利再投资
       * </pre>
       */
      public static final int FuQuan_JiaGeFuQuan_KaoLvHongLi_VALUE = 1;
      /**
       * <code>FuQuan_JiaGeFuQuan_BuKaoLvHongLi = 2;</code>
       *
       * <pre>
       * 价格复权:不考虑红利再投资
       * </pre>
       */
      public static final int FuQuan_JiaGeFuQuan_BuKaoLvHongLi_VALUE = 2;
      /**
       * <code>FuQuan_JingZhiFuQuan_KaoLvHongLi = 3;</code>
       *
       * <pre>
       * 净值复权:考虑红利再投资
       * </pre>
       */
      public static final int FuQuan_JingZhiFuQuan_KaoLvHongLi_VALUE = 3;
      /**
       * <code>FuQuan_JingZhiFuQuan_BuKaoLvHongLi = 4;</code>
       *
       * <pre>
       * 净值复权:不考虑红利再投资
       * </pre>
       */
      public static final int FuQuan_JingZhiFuQuan_BuKaoLvHongLi_VALUE = 4;


      public final int getNumber() { return value; }

      public static EUM_FuQuanLeiXing valueOf(int value) {
        switch (value) {
          case 1: return FuQuan_JiaGeFuQuan_KaoLvHongLi;
          case 2: return FuQuan_JiaGeFuQuan_BuKaoLvHongLi;
          case 3: return FuQuan_JingZhiFuQuan_KaoLvHongLi;
          case 4: return FuQuan_JingZhiFuQuan_BuKaoLvHongLi;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EUM_FuQuanLeiXing>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EUM_FuQuanLeiXing>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EUM_FuQuanLeiXing>() {
              public EUM_FuQuanLeiXing findValueByNumber(int number) {
                return EUM_FuQuanLeiXing.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.getDescriptor().getEnumTypes().get(0);
      }

      private static final EUM_FuQuanLeiXing[] VALUES = values();

      public static EUM_FuQuanLeiXing valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EUM_FuQuanLeiXing(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string obj = 2;
    public static final int OBJ_FIELD_NUMBER = 2;
    private java.lang.Object obj_;
    /**
     * <code>required string obj = 2;</code>
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string obj = 2;</code>
     */
    public java.lang.String getObj() {
      java.lang.Object ref = obj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          obj_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string obj = 2;</code>
     */
    public com.google.protobuf.ByteString
        getObjBytes() {
      java.lang.Object ref = obj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        obj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string chuQuanRiQi = 3;
    public static final int CHUQUANRIQI_FIELD_NUMBER = 3;
    private java.lang.Object chuQuanRiQi_;
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    public boolean hasChuQuanRiQi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    public java.lang.String getChuQuanRiQi() {
      java.lang.Object ref = chuQuanRiQi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chuQuanRiQi_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chuQuanRiQi = 3;</code>
     *
     * <pre>
     * 除权日期
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChuQuanRiQiBytes() {
      java.lang.Object ref = chuQuanRiQi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chuQuanRiQi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];
    public static final int FUQUANLEIXING_FIELD_NUMBER = 4;
    private com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing_;
    /**
     * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
     *
     * <pre>
     * 复权类型
     * </pre>
     */
    public boolean hasFuQuanLeiXing() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
     *
     * <pre>
     * 复权类型
     * </pre>
     */
    public com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing getFuQuanLeiXing() {
      return fuQuanLeiXing_;
    }

    // optional int32 meiGuXianJinFenHong = 5;
    public static final int MEIGUXIANJINFENHONG_FIELD_NUMBER = 5;
    private int meiGuXianJinFenHong_;
    /**
     * <code>optional int32 meiGuXianJinFenHong = 5;</code>
     *
     * <pre>
     * 每股现金分红
     * </pre>
     */
    public boolean hasMeiGuXianJinFenHong() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 meiGuXianJinFenHong = 5;</code>
     *
     * <pre>
     * 每股现金分红
     * </pre>
     */
    public int getMeiGuXianJinFenHong() {
      return meiGuXianJinFenHong_;
    }

    // optional int32 meiGuHongGuShu = 6;
    public static final int MEIGUHONGGUSHU_FIELD_NUMBER = 6;
    private int meiGuHongGuShu_;
    /**
     * <code>optional int32 meiGuHongGuShu = 6;</code>
     *
     * <pre>
     * 每股红股数
     * </pre>
     */
    public boolean hasMeiGuHongGuShu() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 meiGuHongGuShu = 6;</code>
     *
     * <pre>
     * 每股红股数
     * </pre>
     */
    public int getMeiGuHongGuShu() {
      return meiGuHongGuShu_;
    }

    // optional int32 meiGuPeiGuShu = 7;
    public static final int MEIGUPEIGUSHU_FIELD_NUMBER = 7;
    private int meiGuPeiGuShu_;
    /**
     * <code>optional int32 meiGuPeiGuShu = 7;</code>
     *
     * <pre>
     * 每股配股数
     * </pre>
     */
    public boolean hasMeiGuPeiGuShu() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 meiGuPeiGuShu = 7;</code>
     *
     * <pre>
     * 每股配股数
     * </pre>
     */
    public int getMeiGuPeiGuShu() {
      return meiGuPeiGuShu_;
    }

    // optional int32 meiGuPeiGuJia = 8;
    public static final int MEIGUPEIGUJIA_FIELD_NUMBER = 8;
    private int meiGuPeiGuJia_;
    /**
     * <code>optional int32 meiGuPeiGuJia = 8;</code>
     *
     * <pre>
     * 每股配股价
     * </pre>
     */
    public boolean hasMeiGuPeiGuJia() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 meiGuPeiGuJia = 8;</code>
     *
     * <pre>
     * 每股配股价
     * </pre>
     */
    public int getMeiGuPeiGuJia() {
      return meiGuPeiGuJia_;
    }

    // optional int32 meiGuChaiXiShu = 9;
    public static final int MEIGUCHAIXISHU_FIELD_NUMBER = 9;
    private int meiGuChaiXiShu_;
    /**
     * <code>optional int32 meiGuChaiXiShu = 9;</code>
     *
     * <pre>
     * 每股拆细数
     * </pre>
     */
    public boolean hasMeiGuChaiXiShu() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 meiGuChaiXiShu = 9;</code>
     *
     * <pre>
     * 每股拆细数
     * </pre>
     */
    public int getMeiGuChaiXiShu() {
      return meiGuChaiXiShu_;
    }

    // optional int32 tDayClose = 10;
    public static final int TDAYCLOSE_FIELD_NUMBER = 10;
    private int tDayClose_;
    /**
     * <code>optional int32 tDayClose = 10;</code>
     *
     * <pre>
     * t日收盘价
     * </pre>
     */
    public boolean hasTDayClose() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 tDayClose = 10;</code>
     *
     * <pre>
     * t日收盘价
     * </pre>
     */
    public int getTDayClose() {
      return tDayClose_;
    }

    // optional int32 tLastDayClose = 11;
    public static final int TLASTDAYCLOSE_FIELD_NUMBER = 11;
    private int tLastDayClose_;
    /**
     * <code>optional int32 tLastDayClose = 11;</code>
     *
     * <pre>
     * t-1日收盘价
     * </pre>
     */
    public boolean hasTLastDayClose() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 tLastDayClose = 11;</code>
     *
     * <pre>
     * t-1日收盘价
     * </pre>
     */
    public int getTLastDayClose() {
      return tLastDayClose_;
    }

    // optional int32 fuQuanXiShu = 12;
    public static final int FUQUANXISHU_FIELD_NUMBER = 12;
    private int fuQuanXiShu_;
    /**
     * <code>optional int32 fuQuanXiShu = 12;</code>
     *
     * <pre>
     * 复权细数
     * </pre>
     */
    public boolean hasFuQuanXiShu() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 fuQuanXiShu = 12;</code>
     *
     * <pre>
     * 复权细数
     * </pre>
     */
    public int getFuQuanXiShu() {
      return fuQuanXiShu_;
    }

    // optional string tLastDay = 13;
    public static final int TLASTDAY_FIELD_NUMBER = 13;
    private java.lang.Object tLastDay_;
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    public boolean hasTLastDay() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    public java.lang.String getTLastDay() {
      java.lang.Object ref = tLastDay_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tLastDay_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tLastDay = 13;</code>
     *
     * <pre>
     * 除权日的前一个交易日
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTLastDayBytes() {
      java.lang.Object ref = tLastDay_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tLastDay_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 guLiXiShu = 14;
    public static final int GULIXISHU_FIELD_NUMBER = 14;
    private int guLiXiShu_;
    /**
     * <code>optional int32 guLiXiShu = 14;</code>
     *
     * <pre>
     * 股利系数
     * </pre>
     */
    public boolean hasGuLiXiShu() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 guLiXiShu = 14;</code>
     *
     * <pre>
     * 股利系数
     * </pre>
     */
    public int getGuLiXiShu() {
      return guLiXiShu_;
    }

    // optional int32 ziBenXiShu = 15;
    public static final int ZIBENXISHU_FIELD_NUMBER = 15;
    private int ziBenXiShu_;
    /**
     * <code>optional int32 ziBenXiShu = 15;</code>
     *
     * <pre>
     * 资本系数
     * </pre>
     */
    public boolean hasZiBenXiShu() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 ziBenXiShu = 15;</code>
     *
     * <pre>
     * 资本系数
     * </pre>
     */
    public int getZiBenXiShu() {
      return ziBenXiShu_;
    }

    // optional int32 fuQuanXiShuDzh = 16;
    public static final int FUQUANXISHUDZH_FIELD_NUMBER = 16;
    private int fuQuanXiShuDzh_;
    /**
     * <code>optional int32 fuQuanXiShuDzh = 16;</code>
     *
     * <pre>
     * 复权系数(大智慧)
     * </pre>
     */
    public boolean hasFuQuanXiShuDzh() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional int32 fuQuanXiShuDzh = 16;</code>
     *
     * <pre>
     * 复权系数(大智慧)
     * </pre>
     */
    public int getFuQuanXiShuDzh() {
      return fuQuanXiShuDzh_;
    }

    // required string updateTime = 17;
    public static final int UPDATETIME_FIELD_NUMBER = 17;
    private java.lang.Object updateTime_;
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public java.lang.String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          updateTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string updateTime = 17;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      obj_ = "";
      chuQuanRiQi_ = "";
      fuQuanLeiXing_ = com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing.FuQuan_JiaGeFuQuan_BuKaoLvHongLi;
      meiGuXianJinFenHong_ = 0;
      meiGuHongGuShu_ = 0;
      meiGuPeiGuShu_ = 0;
      meiGuPeiGuJia_ = 0;
      meiGuChaiXiShu_ = 0;
      tDayClose_ = 0;
      tLastDayClose_ = 0;
      fuQuanXiShu_ = 0;
      tLastDay_ = "";
      guLiXiShu_ = 0;
      ziBenXiShu_ = 0;
      fuQuanXiShuDzh_ = 0;
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChuQuanRiQi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuQuanLeiXing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getObjBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getChuQuanRiQiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, fuQuanLeiXing_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, meiGuXianJinFenHong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, meiGuHongGuShu_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, meiGuPeiGuShu_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, meiGuPeiGuJia_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, meiGuChaiXiShu_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, tDayClose_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, tLastDayClose_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, fuQuanXiShu_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getTLastDayBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, guLiXiShu_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, ziBenXiShu_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeInt32(16, fuQuanXiShuDzh_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getObjBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getChuQuanRiQiBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, fuQuanLeiXing_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, meiGuXianJinFenHong_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, meiGuHongGuShu_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, meiGuPeiGuShu_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, meiGuPeiGuJia_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, meiGuChaiXiShu_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, tDayClose_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, tLastDayClose_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, fuQuanXiShu_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getTLastDayBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, guLiXiShu_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, ziBenXiShu_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, fuQuanXiShuDzh_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.ChuQuanXinXi}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.ProtoDivideWarrant.internal_static_dzhyun_ChuQuanXinXi_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.ProtoDivideWarrant.internal_static_dzhyun_ChuQuanXinXi_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.class, com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.Builder.class);
      }

      // Construct using com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        obj_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chuQuanRiQi_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fuQuanLeiXing_ = com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing.FuQuan_JiaGeFuQuan_BuKaoLvHongLi;
        bitField0_ = (bitField0_ & ~0x00000008);
        meiGuXianJinFenHong_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        meiGuHongGuShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        meiGuPeiGuShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        meiGuPeiGuJia_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        meiGuChaiXiShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        tDayClose_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        tLastDayClose_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        fuQuanXiShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        tLastDay_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        guLiXiShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        ziBenXiShu_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        fuQuanXiShuDzh_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.ProtoDivideWarrant.internal_static_dzhyun_ChuQuanXinXi_descriptor;
      }

      public com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi getDefaultInstanceForType() {
        return com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.getDefaultInstance();
      }

      public com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi build() {
        com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi buildPartial() {
        com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi result = new com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.obj_ = obj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chuQuanRiQi_ = chuQuanRiQi_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fuQuanLeiXing_ = fuQuanLeiXing_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.meiGuXianJinFenHong_ = meiGuXianJinFenHong_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.meiGuHongGuShu_ = meiGuHongGuShu_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.meiGuPeiGuShu_ = meiGuPeiGuShu_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.meiGuPeiGuJia_ = meiGuPeiGuJia_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.meiGuChaiXiShu_ = meiGuChaiXiShu_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.tDayClose_ = tDayClose_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.tLastDayClose_ = tLastDayClose_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fuQuanXiShu_ = fuQuanXiShu_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.tLastDay_ = tLastDay_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.guLiXiShu_ = guLiXiShu_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.ziBenXiShu_ = ziBenXiShu_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.fuQuanXiShuDzh_ = fuQuanXiShuDzh_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi) {
          return mergeFrom((com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi other) {
        if (other == com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasObj()) {
          bitField0_ |= 0x00000002;
          obj_ = other.obj_;
          onChanged();
        }
        if (other.hasChuQuanRiQi()) {
          bitField0_ |= 0x00000004;
          chuQuanRiQi_ = other.chuQuanRiQi_;
          onChanged();
        }
        if (other.hasFuQuanLeiXing()) {
          setFuQuanLeiXing(other.getFuQuanLeiXing());
        }
        if (other.hasMeiGuXianJinFenHong()) {
          setMeiGuXianJinFenHong(other.getMeiGuXianJinFenHong());
        }
        if (other.hasMeiGuHongGuShu()) {
          setMeiGuHongGuShu(other.getMeiGuHongGuShu());
        }
        if (other.hasMeiGuPeiGuShu()) {
          setMeiGuPeiGuShu(other.getMeiGuPeiGuShu());
        }
        if (other.hasMeiGuPeiGuJia()) {
          setMeiGuPeiGuJia(other.getMeiGuPeiGuJia());
        }
        if (other.hasMeiGuChaiXiShu()) {
          setMeiGuChaiXiShu(other.getMeiGuChaiXiShu());
        }
        if (other.hasTDayClose()) {
          setTDayClose(other.getTDayClose());
        }
        if (other.hasTLastDayClose()) {
          setTLastDayClose(other.getTLastDayClose());
        }
        if (other.hasFuQuanXiShu()) {
          setFuQuanXiShu(other.getFuQuanXiShu());
        }
        if (other.hasTLastDay()) {
          bitField0_ |= 0x00001000;
          tLastDay_ = other.tLastDay_;
          onChanged();
        }
        if (other.hasGuLiXiShu()) {
          setGuLiXiShu(other.getGuLiXiShu());
        }
        if (other.hasZiBenXiShu()) {
          setZiBenXiShu(other.getZiBenXiShu());
        }
        if (other.hasFuQuanXiShuDzh()) {
          setFuQuanXiShuDzh(other.getFuQuanXiShuDzh());
        }
        if (other.hasUpdateTime()) {
          bitField0_ |= 0x00010000;
          updateTime_ = other.updateTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasObj()) {
          
          return false;
        }
        if (!hasChuQuanRiQi()) {
          
          return false;
        }
        if (!hasFuQuanLeiXing()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string obj = 2;
      private java.lang.Object obj_ = "";
      /**
       * <code>required string obj = 2;</code>
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string obj = 2;</code>
       */
      public java.lang.String getObj() {
        java.lang.Object ref = obj_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          obj_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string obj = 2;</code>
       */
      public com.google.protobuf.ByteString
          getObjBytes() {
        java.lang.Object ref = obj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          obj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string obj = 2;</code>
       */
      public Builder setObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string obj = 2;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        obj_ = getDefaultInstance().getObj();
        onChanged();
        return this;
      }
      /**
       * <code>required string obj = 2;</code>
       */
      public Builder setObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        obj_ = value;
        onChanged();
        return this;
      }

      // required string chuQuanRiQi = 3;
      private java.lang.Object chuQuanRiQi_ = "";
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public boolean hasChuQuanRiQi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public java.lang.String getChuQuanRiQi() {
        java.lang.Object ref = chuQuanRiQi_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          chuQuanRiQi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChuQuanRiQiBytes() {
        java.lang.Object ref = chuQuanRiQi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chuQuanRiQi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public Builder setChuQuanRiQi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        chuQuanRiQi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public Builder clearChuQuanRiQi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chuQuanRiQi_ = getDefaultInstance().getChuQuanRiQi();
        onChanged();
        return this;
      }
      /**
       * <code>required string chuQuanRiQi = 3;</code>
       *
       * <pre>
       * 除权日期
       * </pre>
       */
      public Builder setChuQuanRiQiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        chuQuanRiQi_ = value;
        onChanged();
        return this;
      }

      // required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];
      private com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing_ = com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing.FuQuan_JiaGeFuQuan_BuKaoLvHongLi;
      /**
       * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
       *
       * <pre>
       * 复权类型
       * </pre>
       */
      public boolean hasFuQuanLeiXing() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
       *
       * <pre>
       * 复权类型
       * </pre>
       */
      public com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing getFuQuanLeiXing() {
        return fuQuanLeiXing_;
      }
      /**
       * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
       *
       * <pre>
       * 复权类型
       * </pre>
       */
      public Builder setFuQuanLeiXing(com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        fuQuanLeiXing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing fuQuanLeiXing = 4 [default = FuQuan_JiaGeFuQuan_BuKaoLvHongLi];</code>
       *
       * <pre>
       * 复权类型
       * </pre>
       */
      public Builder clearFuQuanLeiXing() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fuQuanLeiXing_ = com.dzhyun.proto.ProtoDivideWarrant.ChuQuanXinXi.EUM_FuQuanLeiXing.FuQuan_JiaGeFuQuan_BuKaoLvHongLi;
        onChanged();
        return this;
      }

      // optional int32 meiGuXianJinFenHong = 5;
      private int meiGuXianJinFenHong_ ;
      /**
       * <code>optional int32 meiGuXianJinFenHong = 5;</code>
       *
       * <pre>
       * 每股现金分红
       * </pre>
       */
      public boolean hasMeiGuXianJinFenHong() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 meiGuXianJinFenHong = 5;</code>
       *
       * <pre>
       * 每股现金分红
       * </pre>
       */
      public int getMeiGuXianJinFenHong() {
        return meiGuXianJinFenHong_;
      }
      /**
       * <code>optional int32 meiGuXianJinFenHong = 5;</code>
       *
       * <pre>
       * 每股现金分红
       * </pre>
       */
      public Builder setMeiGuXianJinFenHong(int value) {
        bitField0_ |= 0x00000010;
        meiGuXianJinFenHong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meiGuXianJinFenHong = 5;</code>
       *
       * <pre>
       * 每股现金分红
       * </pre>
       */
      public Builder clearMeiGuXianJinFenHong() {
        bitField0_ = (bitField0_ & ~0x00000010);
        meiGuXianJinFenHong_ = 0;
        onChanged();
        return this;
      }

      // optional int32 meiGuHongGuShu = 6;
      private int meiGuHongGuShu_ ;
      /**
       * <code>optional int32 meiGuHongGuShu = 6;</code>
       *
       * <pre>
       * 每股红股数
       * </pre>
       */
      public boolean hasMeiGuHongGuShu() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 meiGuHongGuShu = 6;</code>
       *
       * <pre>
       * 每股红股数
       * </pre>
       */
      public int getMeiGuHongGuShu() {
        return meiGuHongGuShu_;
      }
      /**
       * <code>optional int32 meiGuHongGuShu = 6;</code>
       *
       * <pre>
       * 每股红股数
       * </pre>
       */
      public Builder setMeiGuHongGuShu(int value) {
        bitField0_ |= 0x00000020;
        meiGuHongGuShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meiGuHongGuShu = 6;</code>
       *
       * <pre>
       * 每股红股数
       * </pre>
       */
      public Builder clearMeiGuHongGuShu() {
        bitField0_ = (bitField0_ & ~0x00000020);
        meiGuHongGuShu_ = 0;
        onChanged();
        return this;
      }

      // optional int32 meiGuPeiGuShu = 7;
      private int meiGuPeiGuShu_ ;
      /**
       * <code>optional int32 meiGuPeiGuShu = 7;</code>
       *
       * <pre>
       * 每股配股数
       * </pre>
       */
      public boolean hasMeiGuPeiGuShu() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 meiGuPeiGuShu = 7;</code>
       *
       * <pre>
       * 每股配股数
       * </pre>
       */
      public int getMeiGuPeiGuShu() {
        return meiGuPeiGuShu_;
      }
      /**
       * <code>optional int32 meiGuPeiGuShu = 7;</code>
       *
       * <pre>
       * 每股配股数
       * </pre>
       */
      public Builder setMeiGuPeiGuShu(int value) {
        bitField0_ |= 0x00000040;
        meiGuPeiGuShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meiGuPeiGuShu = 7;</code>
       *
       * <pre>
       * 每股配股数
       * </pre>
       */
      public Builder clearMeiGuPeiGuShu() {
        bitField0_ = (bitField0_ & ~0x00000040);
        meiGuPeiGuShu_ = 0;
        onChanged();
        return this;
      }

      // optional int32 meiGuPeiGuJia = 8;
      private int meiGuPeiGuJia_ ;
      /**
       * <code>optional int32 meiGuPeiGuJia = 8;</code>
       *
       * <pre>
       * 每股配股价
       * </pre>
       */
      public boolean hasMeiGuPeiGuJia() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 meiGuPeiGuJia = 8;</code>
       *
       * <pre>
       * 每股配股价
       * </pre>
       */
      public int getMeiGuPeiGuJia() {
        return meiGuPeiGuJia_;
      }
      /**
       * <code>optional int32 meiGuPeiGuJia = 8;</code>
       *
       * <pre>
       * 每股配股价
       * </pre>
       */
      public Builder setMeiGuPeiGuJia(int value) {
        bitField0_ |= 0x00000080;
        meiGuPeiGuJia_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meiGuPeiGuJia = 8;</code>
       *
       * <pre>
       * 每股配股价
       * </pre>
       */
      public Builder clearMeiGuPeiGuJia() {
        bitField0_ = (bitField0_ & ~0x00000080);
        meiGuPeiGuJia_ = 0;
        onChanged();
        return this;
      }

      // optional int32 meiGuChaiXiShu = 9;
      private int meiGuChaiXiShu_ ;
      /**
       * <code>optional int32 meiGuChaiXiShu = 9;</code>
       *
       * <pre>
       * 每股拆细数
       * </pre>
       */
      public boolean hasMeiGuChaiXiShu() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 meiGuChaiXiShu = 9;</code>
       *
       * <pre>
       * 每股拆细数
       * </pre>
       */
      public int getMeiGuChaiXiShu() {
        return meiGuChaiXiShu_;
      }
      /**
       * <code>optional int32 meiGuChaiXiShu = 9;</code>
       *
       * <pre>
       * 每股拆细数
       * </pre>
       */
      public Builder setMeiGuChaiXiShu(int value) {
        bitField0_ |= 0x00000100;
        meiGuChaiXiShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 meiGuChaiXiShu = 9;</code>
       *
       * <pre>
       * 每股拆细数
       * </pre>
       */
      public Builder clearMeiGuChaiXiShu() {
        bitField0_ = (bitField0_ & ~0x00000100);
        meiGuChaiXiShu_ = 0;
        onChanged();
        return this;
      }

      // optional int32 tDayClose = 10;
      private int tDayClose_ ;
      /**
       * <code>optional int32 tDayClose = 10;</code>
       *
       * <pre>
       * t日收盘价
       * </pre>
       */
      public boolean hasTDayClose() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 tDayClose = 10;</code>
       *
       * <pre>
       * t日收盘价
       * </pre>
       */
      public int getTDayClose() {
        return tDayClose_;
      }
      /**
       * <code>optional int32 tDayClose = 10;</code>
       *
       * <pre>
       * t日收盘价
       * </pre>
       */
      public Builder setTDayClose(int value) {
        bitField0_ |= 0x00000200;
        tDayClose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tDayClose = 10;</code>
       *
       * <pre>
       * t日收盘价
       * </pre>
       */
      public Builder clearTDayClose() {
        bitField0_ = (bitField0_ & ~0x00000200);
        tDayClose_ = 0;
        onChanged();
        return this;
      }

      // optional int32 tLastDayClose = 11;
      private int tLastDayClose_ ;
      /**
       * <code>optional int32 tLastDayClose = 11;</code>
       *
       * <pre>
       * t-1日收盘价
       * </pre>
       */
      public boolean hasTLastDayClose() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 tLastDayClose = 11;</code>
       *
       * <pre>
       * t-1日收盘价
       * </pre>
       */
      public int getTLastDayClose() {
        return tLastDayClose_;
      }
      /**
       * <code>optional int32 tLastDayClose = 11;</code>
       *
       * <pre>
       * t-1日收盘价
       * </pre>
       */
      public Builder setTLastDayClose(int value) {
        bitField0_ |= 0x00000400;
        tLastDayClose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tLastDayClose = 11;</code>
       *
       * <pre>
       * t-1日收盘价
       * </pre>
       */
      public Builder clearTLastDayClose() {
        bitField0_ = (bitField0_ & ~0x00000400);
        tLastDayClose_ = 0;
        onChanged();
        return this;
      }

      // optional int32 fuQuanXiShu = 12;
      private int fuQuanXiShu_ ;
      /**
       * <code>optional int32 fuQuanXiShu = 12;</code>
       *
       * <pre>
       * 复权细数
       * </pre>
       */
      public boolean hasFuQuanXiShu() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 fuQuanXiShu = 12;</code>
       *
       * <pre>
       * 复权细数
       * </pre>
       */
      public int getFuQuanXiShu() {
        return fuQuanXiShu_;
      }
      /**
       * <code>optional int32 fuQuanXiShu = 12;</code>
       *
       * <pre>
       * 复权细数
       * </pre>
       */
      public Builder setFuQuanXiShu(int value) {
        bitField0_ |= 0x00000800;
        fuQuanXiShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fuQuanXiShu = 12;</code>
       *
       * <pre>
       * 复权细数
       * </pre>
       */
      public Builder clearFuQuanXiShu() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fuQuanXiShu_ = 0;
        onChanged();
        return this;
      }

      // optional string tLastDay = 13;
      private java.lang.Object tLastDay_ = "";
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public boolean hasTLastDay() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public java.lang.String getTLastDay() {
        java.lang.Object ref = tLastDay_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tLastDay_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTLastDayBytes() {
        java.lang.Object ref = tLastDay_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tLastDay_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public Builder setTLastDay(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        tLastDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public Builder clearTLastDay() {
        bitField0_ = (bitField0_ & ~0x00001000);
        tLastDay_ = getDefaultInstance().getTLastDay();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tLastDay = 13;</code>
       *
       * <pre>
       * 除权日的前一个交易日
       * </pre>
       */
      public Builder setTLastDayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        tLastDay_ = value;
        onChanged();
        return this;
      }

      // optional int32 guLiXiShu = 14;
      private int guLiXiShu_ ;
      /**
       * <code>optional int32 guLiXiShu = 14;</code>
       *
       * <pre>
       * 股利系数
       * </pre>
       */
      public boolean hasGuLiXiShu() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 guLiXiShu = 14;</code>
       *
       * <pre>
       * 股利系数
       * </pre>
       */
      public int getGuLiXiShu() {
        return guLiXiShu_;
      }
      /**
       * <code>optional int32 guLiXiShu = 14;</code>
       *
       * <pre>
       * 股利系数
       * </pre>
       */
      public Builder setGuLiXiShu(int value) {
        bitField0_ |= 0x00002000;
        guLiXiShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 guLiXiShu = 14;</code>
       *
       * <pre>
       * 股利系数
       * </pre>
       */
      public Builder clearGuLiXiShu() {
        bitField0_ = (bitField0_ & ~0x00002000);
        guLiXiShu_ = 0;
        onChanged();
        return this;
      }

      // optional int32 ziBenXiShu = 15;
      private int ziBenXiShu_ ;
      /**
       * <code>optional int32 ziBenXiShu = 15;</code>
       *
       * <pre>
       * 资本系数
       * </pre>
       */
      public boolean hasZiBenXiShu() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 ziBenXiShu = 15;</code>
       *
       * <pre>
       * 资本系数
       * </pre>
       */
      public int getZiBenXiShu() {
        return ziBenXiShu_;
      }
      /**
       * <code>optional int32 ziBenXiShu = 15;</code>
       *
       * <pre>
       * 资本系数
       * </pre>
       */
      public Builder setZiBenXiShu(int value) {
        bitField0_ |= 0x00004000;
        ziBenXiShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ziBenXiShu = 15;</code>
       *
       * <pre>
       * 资本系数
       * </pre>
       */
      public Builder clearZiBenXiShu() {
        bitField0_ = (bitField0_ & ~0x00004000);
        ziBenXiShu_ = 0;
        onChanged();
        return this;
      }

      // optional int32 fuQuanXiShuDzh = 16;
      private int fuQuanXiShuDzh_ ;
      /**
       * <code>optional int32 fuQuanXiShuDzh = 16;</code>
       *
       * <pre>
       * 复权系数(大智慧)
       * </pre>
       */
      public boolean hasFuQuanXiShuDzh() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 fuQuanXiShuDzh = 16;</code>
       *
       * <pre>
       * 复权系数(大智慧)
       * </pre>
       */
      public int getFuQuanXiShuDzh() {
        return fuQuanXiShuDzh_;
      }
      /**
       * <code>optional int32 fuQuanXiShuDzh = 16;</code>
       *
       * <pre>
       * 复权系数(大智慧)
       * </pre>
       */
      public Builder setFuQuanXiShuDzh(int value) {
        bitField0_ |= 0x00008000;
        fuQuanXiShuDzh_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fuQuanXiShuDzh = 16;</code>
       *
       * <pre>
       * 复权系数(大智慧)
       * </pre>
       */
      public Builder clearFuQuanXiShuDzh() {
        bitField0_ = (bitField0_ & ~0x00008000);
        fuQuanXiShuDzh_ = 0;
        onChanged();
        return this;
      }

      // required string updateTime = 17;
      private java.lang.Object updateTime_ = "";
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public java.lang.String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        java.lang.Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder setUpdateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00010000);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string updateTime = 17;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        updateTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.ChuQuanXinXi)
    }

    static {
      defaultInstance = new ChuQuanXinXi(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.ChuQuanXinXi)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_ChuQuanXinXi_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_ChuQuanXinXi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025CldChuQuanXinXi.proto\022\006dzhyun\"\352\004\n\014ChuQ" +
      "uanXinXi\022\n\n\002id\030\001 \002(\005\022\013\n\003obj\030\002 \002(\t\022\023\n\013chu" +
      "QuanRiQi\030\003 \002(\t\022_\n\rfuQuanLeiXing\030\004 \002(\0162&." +
      "dzhyun.ChuQuanXinXi.EUM_FuQuanLeiXing: F" +
      "uQuan_JiaGeFuQuan_BuKaoLvHongLi\022\033\n\023meiGu" +
      "XianJinFenHong\030\005 \001(\005\022\026\n\016meiGuHongGuShu\030\006" +
      " \001(\005\022\025\n\rmeiGuPeiGuShu\030\007 \001(\005\022\025\n\rmeiGuPeiG" +
      "uJia\030\010 \001(\005\022\026\n\016meiGuChaiXiShu\030\t \001(\005\022\021\n\ttD" +
      "ayClose\030\n \001(\005\022\025\n\rtLastDayClose\030\013 \001(\005\022\023\n\013" +
      "fuQuanXiShu\030\014 \001(\005\022\020\n\010tLastDay\030\r \001(\t\022\021\n\tg",
      "uLiXiShu\030\016 \001(\005\022\022\n\nziBenXiShu\030\017 \001(\005\022\026\n\016fu" +
      "QuanXiShuDzh\030\020 \001(\005\022\022\n\nupdateTime\030\021 \002(\t\"\253" +
      "\001\n\021EUM_FuQuanLeiXing\022\"\n\036FuQuan_JiaGeFuQu" +
      "an_KaoLvHongLi\020\001\022$\n FuQuan_JiaGeFuQuan_B" +
      "uKaoLvHongLi\020\002\022$\n FuQuan_JingZhiFuQuan_K" +
      "aoLvHongLi\020\003\022&\n\"FuQuan_JingZhiFuQuan_BuK" +
      "aoLvHongLi\020\004B&\n\020com.dzhyun.protoB\022ProtoD" +
      "ivideWarrant"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dzhyun_ChuQuanXinXi_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dzhyun_ChuQuanXinXi_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_ChuQuanXinXi_descriptor,
              new java.lang.String[] { "Id", "Obj", "ChuQuanRiQi", "FuQuanLeiXing", "MeiGuXianJinFenHong", "MeiGuHongGuShu", "MeiGuPeiGuShu", "MeiGuPeiGuJia", "MeiGuChaiXiShu", "TDayClose", "TLastDayClose", "FuQuanXiShu", "TLastDay", "GuLiXiShu", "ZiBenXiShu", "FuQuanXiShuDzh", "UpdateTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
