// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CldJiaoYiSuoShuXing.proto

package com.dzhyun.proto;

public final class ProtoExchangeProperty {
  private ProtoExchangeProperty() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JiaoYiSuoShuXingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    int getId();

    // required string oCode = 2;
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    boolean hasOCode();
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    java.lang.String getOCode();
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    com.google.protobuf.ByteString
        getOCodeBytes();

    // required string zhongWenJianCheng = 3;
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    boolean hasZhongWenJianCheng();
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    java.lang.String getZhongWenJianCheng();
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    com.google.protobuf.ByteString
        getZhongWenJianChengBytes();

    // required string tongYongMing = 4;
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    boolean hasTongYongMing();
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    java.lang.String getTongYongMing();
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    com.google.protobuf.ByteString
        getTongYongMingBytes();

    // required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];
    /**
     * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
     *
     * <pre>
     * 国家
     * </pre>
     */
    boolean hasGuoJia();
    /**
     * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
     *
     * <pre>
     * 国家
     * </pre>
     */
    com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia getGuoJia();

    // required string qianZhui = 6;
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    boolean hasQianZhui();
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    java.lang.String getQianZhui();
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    com.google.protobuf.ByteString
        getQianZhuiBytes();

    // required string updateTime = 7;
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    boolean hasUpdateTime();
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    java.lang.String getUpdateTime();
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();
  }
  /**
   * Protobuf type {@code dzhyun.JiaoYiSuoShuXing}
   *
   * <pre>
   * 交易所-交易所属性 
   * </pre>
   */
  public static final class JiaoYiSuoShuXing extends
      com.google.protobuf.GeneratedMessage
      implements JiaoYiSuoShuXingOrBuilder {
    // Use JiaoYiSuoShuXing.newBuilder() to construct.
    private JiaoYiSuoShuXing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JiaoYiSuoShuXing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JiaoYiSuoShuXing defaultInstance;
    public static JiaoYiSuoShuXing getDefaultInstance() {
      return defaultInstance;
    }

    public JiaoYiSuoShuXing getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JiaoYiSuoShuXing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              oCode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              zhongWenJianCheng_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              tongYongMing_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia value = com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                guoJia_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              qianZhui_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.ProtoExchangeProperty.internal_static_dzhyun_JiaoYiSuoShuXing_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.ProtoExchangeProperty.internal_static_dzhyun_JiaoYiSuoShuXing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.class, com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.Builder.class);
    }

    public static com.google.protobuf.Parser<JiaoYiSuoShuXing> PARSER =
        new com.google.protobuf.AbstractParser<JiaoYiSuoShuXing>() {
      public JiaoYiSuoShuXing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JiaoYiSuoShuXing(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JiaoYiSuoShuXing> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code dzhyun.JiaoYiSuoShuXing.EUM_guoJia}
     *
     * <pre>
     * 枚举类型-国家
     * </pre>
     */
    public enum EUM_guoJia
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ZhongGuo = 1;</code>
       *
       * <pre>
       * 中国
       * </pre>
       */
      ZhongGuo(0, 1),
      /**
       * <code>ZhongGuo_HK = 2;</code>
       *
       * <pre>
       * 中国-香港
       * </pre>
       */
      ZhongGuo_HK(1, 2),
      /**
       * <code>ZhongGuo_TW = 3;</code>
       *
       * <pre>
       * 中国-台湾
       * </pre>
       */
      ZhongGuo_TW(2, 3),
      /**
       * <code>MeiGuo = 4;</code>
       *
       * <pre>
       * 美国
       * </pre>
       */
      MeiGuo(3, 4),
      /**
       * <code>RiBen = 5;</code>
       *
       * <pre>
       * 日本
       * </pre>
       */
      RiBen(4, 5),
      ;

      /**
       * <code>ZhongGuo = 1;</code>
       *
       * <pre>
       * 中国
       * </pre>
       */
      public static final int ZhongGuo_VALUE = 1;
      /**
       * <code>ZhongGuo_HK = 2;</code>
       *
       * <pre>
       * 中国-香港
       * </pre>
       */
      public static final int ZhongGuo_HK_VALUE = 2;
      /**
       * <code>ZhongGuo_TW = 3;</code>
       *
       * <pre>
       * 中国-台湾
       * </pre>
       */
      public static final int ZhongGuo_TW_VALUE = 3;
      /**
       * <code>MeiGuo = 4;</code>
       *
       * <pre>
       * 美国
       * </pre>
       */
      public static final int MeiGuo_VALUE = 4;
      /**
       * <code>RiBen = 5;</code>
       *
       * <pre>
       * 日本
       * </pre>
       */
      public static final int RiBen_VALUE = 5;


      public final int getNumber() { return value; }

      public static EUM_guoJia valueOf(int value) {
        switch (value) {
          case 1: return ZhongGuo;
          case 2: return ZhongGuo_HK;
          case 3: return ZhongGuo_TW;
          case 4: return MeiGuo;
          case 5: return RiBen;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EUM_guoJia>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EUM_guoJia>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EUM_guoJia>() {
              public EUM_guoJia findValueByNumber(int number) {
                return EUM_guoJia.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.getDescriptor().getEnumTypes().get(0);
      }

      private static final EUM_guoJia[] VALUES = values();

      public static EUM_guoJia valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EUM_guoJia(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dzhyun.JiaoYiSuoShuXing.EUM_guoJia)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required string oCode = 2;
    public static final int OCODE_FIELD_NUMBER = 2;
    private java.lang.Object oCode_;
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    public boolean hasOCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    public java.lang.String getOCode() {
      java.lang.Object ref = oCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          oCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string oCode = 2;</code>
     *
     * <pre>
     * 交易所代码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOCodeBytes() {
      java.lang.Object ref = oCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string zhongWenJianCheng = 3;
    public static final int ZHONGWENJIANCHENG_FIELD_NUMBER = 3;
    private java.lang.Object zhongWenJianCheng_;
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    public boolean hasZhongWenJianCheng() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    public java.lang.String getZhongWenJianCheng() {
      java.lang.Object ref = zhongWenJianCheng_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zhongWenJianCheng_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string zhongWenJianCheng = 3;</code>
     *
     * <pre>
     * 中文简称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getZhongWenJianChengBytes() {
      java.lang.Object ref = zhongWenJianCheng_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zhongWenJianCheng_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string tongYongMing = 4;
    public static final int TONGYONGMING_FIELD_NUMBER = 4;
    private java.lang.Object tongYongMing_;
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    public boolean hasTongYongMing() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    public java.lang.String getTongYongMing() {
      java.lang.Object ref = tongYongMing_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tongYongMing_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tongYongMing = 4;</code>
     *
     * <pre>
     * 通用名
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTongYongMingBytes() {
      java.lang.Object ref = tongYongMing_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tongYongMing_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];
    public static final int GUOJIA_FIELD_NUMBER = 5;
    private com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia guoJia_;
    /**
     * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
     *
     * <pre>
     * 国家
     * </pre>
     */
    public boolean hasGuoJia() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
     *
     * <pre>
     * 国家
     * </pre>
     */
    public com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia getGuoJia() {
      return guoJia_;
    }

    // required string qianZhui = 6;
    public static final int QIANZHUI_FIELD_NUMBER = 6;
    private java.lang.Object qianZhui_;
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    public boolean hasQianZhui() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    public java.lang.String getQianZhui() {
      java.lang.Object ref = qianZhui_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          qianZhui_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string qianZhui = 6;</code>
     *
     * <pre>
     * 前缀
     * </pre>
     */
    public com.google.protobuf.ByteString
        getQianZhuiBytes() {
      java.lang.Object ref = qianZhui_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        qianZhui_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string updateTime = 7;
    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private java.lang.Object updateTime_;
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public java.lang.String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          updateTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string updateTime = 7;</code>
     *
     * <pre>
     * 更新时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      oCode_ = "";
      zhongWenJianCheng_ = "";
      tongYongMing_ = "";
      guoJia_ = com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia.ZhongGuo;
      qianZhui_ = "";
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZhongWenJianCheng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTongYongMing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGuoJia()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQianZhui()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getOCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getZhongWenJianChengBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTongYongMingBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, guoJia_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getQianZhuiBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getOCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getZhongWenJianChengBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTongYongMingBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, guoJia_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getQianZhuiBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.JiaoYiSuoShuXing}
     *
     * <pre>
     * 交易所-交易所属性 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.ProtoExchangeProperty.internal_static_dzhyun_JiaoYiSuoShuXing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.ProtoExchangeProperty.internal_static_dzhyun_JiaoYiSuoShuXing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.class, com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.Builder.class);
      }

      // Construct using com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        oCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        zhongWenJianCheng_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tongYongMing_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        guoJia_ = com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia.ZhongGuo;
        bitField0_ = (bitField0_ & ~0x00000010);
        qianZhui_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.ProtoExchangeProperty.internal_static_dzhyun_JiaoYiSuoShuXing_descriptor;
      }

      public com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing getDefaultInstanceForType() {
        return com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.getDefaultInstance();
      }

      public com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing build() {
        com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing buildPartial() {
        com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing result = new com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.oCode_ = oCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.zhongWenJianCheng_ = zhongWenJianCheng_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tongYongMing_ = tongYongMing_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.guoJia_ = guoJia_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.qianZhui_ = qianZhui_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing) {
          return mergeFrom((com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing other) {
        if (other == com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOCode()) {
          bitField0_ |= 0x00000002;
          oCode_ = other.oCode_;
          onChanged();
        }
        if (other.hasZhongWenJianCheng()) {
          bitField0_ |= 0x00000004;
          zhongWenJianCheng_ = other.zhongWenJianCheng_;
          onChanged();
        }
        if (other.hasTongYongMing()) {
          bitField0_ |= 0x00000008;
          tongYongMing_ = other.tongYongMing_;
          onChanged();
        }
        if (other.hasGuoJia()) {
          setGuoJia(other.getGuoJia());
        }
        if (other.hasQianZhui()) {
          bitField0_ |= 0x00000020;
          qianZhui_ = other.qianZhui_;
          onChanged();
        }
        if (other.hasUpdateTime()) {
          bitField0_ |= 0x00000040;
          updateTime_ = other.updateTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasOCode()) {
          
          return false;
        }
        if (!hasZhongWenJianCheng()) {
          
          return false;
        }
        if (!hasTongYongMing()) {
          
          return false;
        }
        if (!hasGuoJia()) {
          
          return false;
        }
        if (!hasQianZhui()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string oCode = 2;
      private java.lang.Object oCode_ = "";
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public boolean hasOCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public java.lang.String getOCode() {
        java.lang.Object ref = oCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          oCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOCodeBytes() {
        java.lang.Object ref = oCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public Builder setOCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public Builder clearOCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oCode_ = getDefaultInstance().getOCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string oCode = 2;</code>
       *
       * <pre>
       * 交易所代码
       * </pre>
       */
      public Builder setOCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        oCode_ = value;
        onChanged();
        return this;
      }

      // required string zhongWenJianCheng = 3;
      private java.lang.Object zhongWenJianCheng_ = "";
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public boolean hasZhongWenJianCheng() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public java.lang.String getZhongWenJianCheng() {
        java.lang.Object ref = zhongWenJianCheng_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          zhongWenJianCheng_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getZhongWenJianChengBytes() {
        java.lang.Object ref = zhongWenJianCheng_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zhongWenJianCheng_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public Builder setZhongWenJianCheng(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zhongWenJianCheng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public Builder clearZhongWenJianCheng() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zhongWenJianCheng_ = getDefaultInstance().getZhongWenJianCheng();
        onChanged();
        return this;
      }
      /**
       * <code>required string zhongWenJianCheng = 3;</code>
       *
       * <pre>
       * 中文简称
       * </pre>
       */
      public Builder setZhongWenJianChengBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zhongWenJianCheng_ = value;
        onChanged();
        return this;
      }

      // required string tongYongMing = 4;
      private java.lang.Object tongYongMing_ = "";
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public boolean hasTongYongMing() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public java.lang.String getTongYongMing() {
        java.lang.Object ref = tongYongMing_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tongYongMing_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTongYongMingBytes() {
        java.lang.Object ref = tongYongMing_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tongYongMing_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public Builder setTongYongMing(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tongYongMing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public Builder clearTongYongMing() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tongYongMing_ = getDefaultInstance().getTongYongMing();
        onChanged();
        return this;
      }
      /**
       * <code>required string tongYongMing = 4;</code>
       *
       * <pre>
       * 通用名
       * </pre>
       */
      public Builder setTongYongMingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        tongYongMing_ = value;
        onChanged();
        return this;
      }

      // required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];
      private com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia guoJia_ = com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia.ZhongGuo;
      /**
       * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
       *
       * <pre>
       * 国家
       * </pre>
       */
      public boolean hasGuoJia() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
       *
       * <pre>
       * 国家
       * </pre>
       */
      public com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia getGuoJia() {
        return guoJia_;
      }
      /**
       * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
       *
       * <pre>
       * 国家
       * </pre>
       */
      public Builder setGuoJia(com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        guoJia_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .dzhyun.JiaoYiSuoShuXing.EUM_guoJia guoJia = 5 [default = ZhongGuo];</code>
       *
       * <pre>
       * 国家
       * </pre>
       */
      public Builder clearGuoJia() {
        bitField0_ = (bitField0_ & ~0x00000010);
        guoJia_ = com.dzhyun.proto.ProtoExchangeProperty.JiaoYiSuoShuXing.EUM_guoJia.ZhongGuo;
        onChanged();
        return this;
      }

      // required string qianZhui = 6;
      private java.lang.Object qianZhui_ = "";
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public boolean hasQianZhui() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public java.lang.String getQianZhui() {
        java.lang.Object ref = qianZhui_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          qianZhui_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public com.google.protobuf.ByteString
          getQianZhuiBytes() {
        java.lang.Object ref = qianZhui_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          qianZhui_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public Builder setQianZhui(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        qianZhui_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public Builder clearQianZhui() {
        bitField0_ = (bitField0_ & ~0x00000020);
        qianZhui_ = getDefaultInstance().getQianZhui();
        onChanged();
        return this;
      }
      /**
       * <code>required string qianZhui = 6;</code>
       *
       * <pre>
       * 前缀
       * </pre>
       */
      public Builder setQianZhuiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        qianZhui_ = value;
        onChanged();
        return this;
      }

      // required string updateTime = 7;
      private java.lang.Object updateTime_ = "";
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public java.lang.String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        java.lang.Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder setUpdateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string updateTime = 7;</code>
       *
       * <pre>
       * 更新时间
       * </pre>
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        updateTime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.JiaoYiSuoShuXing)
    }

    static {
      defaultInstance = new JiaoYiSuoShuXing(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.JiaoYiSuoShuXing)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_JiaoYiSuoShuXing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_JiaoYiSuoShuXing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CldJiaoYiSuoShuXing.proto\022\006dzhyun\"\230\002\n\020" +
      "JiaoYiSuoShuXing\022\n\n\002id\030\001 \002(\005\022\r\n\005oCode\030\002 " +
      "\002(\t\022\031\n\021zhongWenJianCheng\030\003 \002(\t\022\024\n\014tongYo" +
      "ngMing\030\004 \002(\t\022=\n\006guoJia\030\005 \002(\0162#.dzhyun.Ji" +
      "aoYiSuoShuXing.EUM_guoJia:\010ZhongGuo\022\020\n\010q" +
      "ianZhui\030\006 \002(\t\022\022\n\nupdateTime\030\007 \002(\t\"S\n\nEUM" +
      "_guoJia\022\014\n\010ZhongGuo\020\001\022\017\n\013ZhongGuo_HK\020\002\022\017" +
      "\n\013ZhongGuo_TW\020\003\022\n\n\006MeiGuo\020\004\022\t\n\005RiBen\020\005B)" +
      "\n\020com.dzhyun.protoB\025ProtoExchangePropert" +
      "y"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dzhyun_JiaoYiSuoShuXing_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dzhyun_JiaoYiSuoShuXing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_JiaoYiSuoShuXing_descriptor,
              new java.lang.String[] { "Id", "OCode", "ZhongWenJianCheng", "TongYongMing", "GuoJia", "QianZhui", "UpdateTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
