// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package com.gw.dzhyun.svc.statistics;

//http://dms.gw.com.cn/pages/viewpage.action?pageId=131826300
/*
 * message TongjiZhangDiePingJiaShu
{
  required int64 ShiJian;
  required int64 JiaShu;
}
message TongjiChengJiaoE
{
  required int64 ShiJian;
  required int64 ChengJiaoE;
}
此PROBUFF对的java实现类
详见http://dms.gw.com.cn/pages/viewpage.action?pageId=131826300
 */
public final class Statistics {
  private Statistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TongjiZhangDiePingJiaShuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.TongjiZhangDiePingJiaShu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    boolean hasShiJian();
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    long getShiJian();

    /**
     * <code>required int64 JiaShu = 2;</code>
     */
    boolean hasJiaShu();
    /**
     * <code>required int64 JiaShu = 2;</code>
     */
    long getJiaShu();
  }
  /**
   * Protobuf type {@code dzhyun.TongjiZhangDiePingJiaShu}
   */
  public static final class TongjiZhangDiePingJiaShu extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.TongjiZhangDiePingJiaShu)
      TongjiZhangDiePingJiaShuOrBuilder {
    // Use TongjiZhangDiePingJiaShu.newBuilder() to construct.
    private TongjiZhangDiePingJiaShu(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TongjiZhangDiePingJiaShu(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TongjiZhangDiePingJiaShu defaultInstance;
    public static TongjiZhangDiePingJiaShu getDefaultInstance() {
      return defaultInstance;
    }

    public TongjiZhangDiePingJiaShu getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TongjiZhangDiePingJiaShu(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              shiJian_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jiaShu_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiZhangDiePingJiaShu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.class, com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.Builder.class);
    }

    public static com.google.protobuf.Parser<TongjiZhangDiePingJiaShu> PARSER =
        new com.google.protobuf.AbstractParser<TongjiZhangDiePingJiaShu>() {
      public TongjiZhangDiePingJiaShu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TongjiZhangDiePingJiaShu(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TongjiZhangDiePingJiaShu> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SHIJIAN_FIELD_NUMBER = 1;
    private long shiJian_;
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    public boolean hasShiJian() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    public long getShiJian() {
      return shiJian_;
    }

    public static final int JIASHU_FIELD_NUMBER = 2;
    private long jiaShu_;
    /**
     * <code>required int64 JiaShu = 2;</code>
     */
    public boolean hasJiaShu() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 JiaShu = 2;</code>
     */
    public long getJiaShu() {
      return jiaShu_;
    }

    private void initFields() {
      shiJian_ = 0L;
      jiaShu_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasShiJian()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJiaShu()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, shiJian_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, jiaShu_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, shiJian_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, jiaShu_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.TongjiZhangDiePingJiaShu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.TongjiZhangDiePingJiaShu)
        com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiZhangDiePingJiaShu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.class, com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.Builder.class);
      }

      // Construct using com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        shiJian_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        jiaShu_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor;
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu getDefaultInstanceForType() {
        return com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.getDefaultInstance();
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu build() {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu buildPartial() {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu result = new com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shiJian_ = shiJian_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jiaShu_ = jiaShu_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu) {
          return mergeFrom((com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu other) {
        if (other == com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu.getDefaultInstance()) return this;
        if (other.hasShiJian()) {
          setShiJian(other.getShiJian());
        }
        if (other.hasJiaShu()) {
          setJiaShu(other.getJiaShu());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasShiJian()) {
          
          return false;
        }
        if (!hasJiaShu()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.dzhyun.svc.statistics.Statistics.TongjiZhangDiePingJiaShu) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long shiJian_ ;
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public boolean hasShiJian() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public long getShiJian() {
        return shiJian_;
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public Builder setShiJian(long value) {
        bitField0_ |= 0x00000001;
        shiJian_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public Builder clearShiJian() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shiJian_ = 0L;
        onChanged();
        return this;
      }

      private long jiaShu_ ;
      /**
       * <code>required int64 JiaShu = 2;</code>
       */
      public boolean hasJiaShu() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 JiaShu = 2;</code>
       */
      public long getJiaShu() {
        return jiaShu_;
      }
      /**
       * <code>required int64 JiaShu = 2;</code>
       */
      public Builder setJiaShu(long value) {
        bitField0_ |= 0x00000002;
        jiaShu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 JiaShu = 2;</code>
       */
      public Builder clearJiaShu() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jiaShu_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.TongjiZhangDiePingJiaShu)
    }

    static {
      defaultInstance = new TongjiZhangDiePingJiaShu(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.TongjiZhangDiePingJiaShu)
  }

  public interface TongjiChengJiaoEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dzhyun.TongjiChengJiaoE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    boolean hasShiJian();
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    long getShiJian();

    /**
     * <code>required int64 ChengJiaoE = 2;</code>
     */
    boolean hasChengJiaoE();
    /**
     * <code>required int64 ChengJiaoE = 2;</code>
     */
    long getChengJiaoE();
  }
  /**
   * Protobuf type {@code dzhyun.TongjiChengJiaoE}
   */
  public static final class TongjiChengJiaoE extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dzhyun.TongjiChengJiaoE)
      TongjiChengJiaoEOrBuilder {
    // Use TongjiChengJiaoE.newBuilder() to construct.
    private TongjiChengJiaoE(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TongjiChengJiaoE(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TongjiChengJiaoE defaultInstance;
    public static TongjiChengJiaoE getDefaultInstance() {
      return defaultInstance;
    }

    public TongjiChengJiaoE getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TongjiChengJiaoE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              shiJian_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              chengJiaoE_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiChengJiaoE_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiChengJiaoE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.class, com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.Builder.class);
    }

    public static com.google.protobuf.Parser<TongjiChengJiaoE> PARSER =
        new com.google.protobuf.AbstractParser<TongjiChengJiaoE>() {
      public TongjiChengJiaoE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TongjiChengJiaoE(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TongjiChengJiaoE> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SHIJIAN_FIELD_NUMBER = 1;
    private long shiJian_;
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    public boolean hasShiJian() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 ShiJian = 1;</code>
     */
    public long getShiJian() {
      return shiJian_;
    }

    public static final int CHENGJIAOE_FIELD_NUMBER = 2;
    private long chengJiaoE_;
    /**
     * <code>required int64 ChengJiaoE = 2;</code>
     */
    public boolean hasChengJiaoE() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 ChengJiaoE = 2;</code>
     */
    public long getChengJiaoE() {
      return chengJiaoE_;
    }

    private void initFields() {
      shiJian_ = 0L;
      chengJiaoE_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasShiJian()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChengJiaoE()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, shiJian_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, chengJiaoE_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, shiJian_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, chengJiaoE_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.TongjiChengJiaoE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dzhyun.TongjiChengJiaoE)
        com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiChengJiaoE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiChengJiaoE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.class, com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.Builder.class);
      }

      // Construct using com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        shiJian_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        chengJiaoE_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gw.dzhyun.svc.statistics.Statistics.internal_static_dzhyun_TongjiChengJiaoE_descriptor;
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE getDefaultInstanceForType() {
        return com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.getDefaultInstance();
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE build() {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE buildPartial() {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE result = new com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shiJian_ = shiJian_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chengJiaoE_ = chengJiaoE_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE) {
          return mergeFrom((com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE other) {
        if (other == com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE.getDefaultInstance()) return this;
        if (other.hasShiJian()) {
          setShiJian(other.getShiJian());
        }
        if (other.hasChengJiaoE()) {
          setChengJiaoE(other.getChengJiaoE());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasShiJian()) {
          
          return false;
        }
        if (!hasChengJiaoE()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.dzhyun.svc.statistics.Statistics.TongjiChengJiaoE) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long shiJian_ ;
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public boolean hasShiJian() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public long getShiJian() {
        return shiJian_;
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public Builder setShiJian(long value) {
        bitField0_ |= 0x00000001;
        shiJian_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ShiJian = 1;</code>
       */
      public Builder clearShiJian() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shiJian_ = 0L;
        onChanged();
        return this;
      }

      private long chengJiaoE_ ;
      /**
       * <code>required int64 ChengJiaoE = 2;</code>
       */
      public boolean hasChengJiaoE() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 ChengJiaoE = 2;</code>
       */
      public long getChengJiaoE() {
        return chengJiaoE_;
      }
      /**
       * <code>required int64 ChengJiaoE = 2;</code>
       */
      public Builder setChengJiaoE(long value) {
        bitField0_ |= 0x00000002;
        chengJiaoE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ChengJiaoE = 2;</code>
       */
      public Builder clearChengJiaoE() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chengJiaoE_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.TongjiChengJiaoE)
    }

    static {
      defaultInstance = new TongjiChengJiaoE(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.TongjiChengJiaoE)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_TongjiZhangDiePingJiaShu_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_TongjiChengJiaoE_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_TongjiChengJiaoE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020statistics.proto\022\006dzhyun\";\n\030TongjiZhan" +
      "gDiePingJiaShu\022\017\n\007ShiJian\030\001 \002(\003\022\016\n\006JiaSh" +
      "u\030\002 \002(\003\"7\n\020TongjiChengJiaoE\022\017\n\007ShiJian\030\001" +
      " \002(\003\022\022\n\nChengJiaoE\030\002 \002(\003B\036\n\034com.gw.dzhyu" +
      "n.svc.statictics"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dzhyun_TongjiZhangDiePingJiaShu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_TongjiZhangDiePingJiaShu_descriptor,
        new java.lang.String[] { "ShiJian", "JiaShu", });
    internal_static_dzhyun_TongjiChengJiaoE_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dzhyun_TongjiChengJiaoE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dzhyun_TongjiChengJiaoE_descriptor,
        new java.lang.String[] { "ShiJian", "ChengJiaoE", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
